<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="manage-events.aspx.cs" Inherits="KBEC.manage_events" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">

    <title>Manage Events</title>

    <link rel="stylesheet" href="Content/kbec.css" />

    <style>

        body{
            background:#0b0f14;
            color:white;
            font-family:Arial;
        }

        .manage-container{
            width:95%;
            max-width:1200px;
            margin:120px auto;
        }

        .top-bar{
            display:flex;
            justify-content:space-between;
            align-items:center;
            margin-bottom:30px;
        }

        .top-bar h1{
            color:#f5c518;
        }

        .btn-back{
            background:#f5c518;
            color:black;
            padding:12px 20px;
            border-radius:8px;
            text-decoration:none;
            font-weight:bold;
        }

        .grid{
            width:100%;
            border-collapse:collapse;
            background:#111;
        }

        .grid th{
            background:#f5c518;
            color:black;
            padding:14px;
        }

        .grid td{
            padding:12px;
            border-bottom:1px solid #333;
        }

        .grid input{
            width:100%;
            padding:8px;
            background:#1a1a1a;
            color:white;
            border:1px solid #444;
            border-radius:6px;
        }

    </style>

</head>

<body>

<form id="form1" runat="server">

<div class="manage-container">

    <div class="top-bar">

        <h1>Manage Events</h1>

        <a href="admin-dashboard.aspx" class="btn-back">
            Back To Dashboard
        </a>

    </div>
    <asp:GridView
    ID="gvEvents"
    runat="server"
    CssClass="grid"
    AutoGenerateColumns="False"
    DataKeyNames="EventID"
    AutoGenerateEditButton="True"
    AutoGenerateDeleteButton="True"
    OnRowEditing="gvEvents_RowEditing"
    OnRowCancelingEdit="gvEvents_RowCancelingEdit"
    OnRowUpdating="gvEvents_RowUpdating"
    OnRowDeleting="gvEvents_RowDeleting">

    <Columns>

        <asp:BoundField
            DataField="EventID"
            HeaderText="ID"
            ReadOnly="True" />

     
        <asp:TemplateField HeaderText="Title">

            <ItemTemplate>
                <%# Eval("Title") %>
            </ItemTemplate>

            <EditItemTemplate>

                <asp:TextBox
                    ID="txtTitle"
                    runat="server"
                    Text='<%# Bind("Title") %>' />

            </EditItemTemplate>

        </asp:TemplateField>

       
        <asp:TemplateField HeaderText="Description">

            <ItemTemplate>
                <%# Eval("Description") %>
            </ItemTemplate>

            <EditItemTemplate>

                <asp:TextBox
                    ID="txtDescription"
                    runat="server"
                    Text='<%# Bind("Description") %>' />

            </EditItemTemplate>

        </asp:TemplateField>

       
        <asp:TemplateField HeaderText="Location">

            <ItemTemplate>
                <%# Eval("Location") %>
            </ItemTemplate>

            <EditItemTemplate>

                <asp:TextBox
                    ID="txtLocation"
                    runat="server"
                    Text='<%# Bind("Location") %>' />

            </EditItemTemplate>

        </asp:TemplateField>

      
        <asp:TemplateField HeaderText="Image">

            <ItemTemplate>

                <img src='Images/<%# Eval("ImagePath") %>'
                    width="120"
                    style="border-radius:10px;" />

            </ItemTemplate>

            <EditItemTemplate>

                <asp:FileUpload
                    ID="fuEditImage"
                    runat="server" />

            </EditItemTemplate>

        </asp:TemplateField>

       
        <asp:TemplateField HeaderText="Event Key">

            <ItemTemplate>
                <%# Eval("EventKey") %>
            </ItemTemplate>

            <EditItemTemplate>

                <asp:TextBox
                    ID="txtEventKey"
                    runat="server"
                    Text='<%# Bind("EventKey") %>' />

            </EditItemTemplate>

        </asp:TemplateField>

    </Columns>

</asp:GridView>

</div>

</form>

</body>
</html>